### ISSUE TITLE
油矿那边服务超级不稳定，经常打不开

### ISSUE THREAD

**Issue by henryatman** [AlphaSmartDog/DeepLearningNotes#5]
油矿那边服务超级不稳定，经常打不开

希望大佬多把文章放到github来，感谢分享

另外，大佬是用什么机器跑的？自己构建的 intel i7+GTX1080+ubuntu 游戏主机么

**Comment by AlphaSmartDog** [comment]
小数据在740笔记本卡上跑的，稍大一点数据用的单卡1080Ti，更大的数据在集群跑的，这个目录的下的代码应该用不到。
