### ISSUE TITLE
强化学习的例子都是做日频的 可以做小周期吗

### ISSUE THREAD

**Issue by shushan2017** [AlphaSmartDog/DeepLearningNotes#6]
看数据准备部分  没想到该怎么套用小周期交易

**Comment by AlphaSmartDog** [comment]
小周期交易指的是什么？期货的日内策略还是多股票日内回转？

**Comment by shushan2017** [comment]
您好 谢谢回复 小周期我是指期货日内  因为期货做日频感觉比较受限制  也少了很多进出机会 至少不是最优解 看您的强化学习的代码  都是用一天的5分钟数据 以次日的开盘收盘计算收益
能否用5分钟的数据  直接学习收益最大化呢  而不管另外的周期（日线） 像您的dnc代码那样  甚至用1分钟的数据。。。。
再次感谢

**Comment by AlphaSmartDog** [comment]
明白你意思，这个主要是强化学习需要比较大的算力，而且不是很稳定，做到日内交易不是很好操控，你可以自行搞搞，理论上是可以的。
如果算力可观的话，也可以这么做。
